__title__ = 'fwdcontracts'
__description__ = 'Upvest smart contract forwarding tools'
__url__ = 'https://github.com/toknapp/contracts'
__version__ = '1.0.0'
__author__ = 'Upvest GmbH'
__author_email__ = 'tech@upvest.co'
__license__ = 'MIT'
