#!/bin/sh

set -o errexit -o pipefail

COMPILER=${COMPILER:-evm}
INPUT=
while getopts "s:vi:" opt; do
    case $opt in
        s) SOLC=$OPTARG ;;
        v) VERBOSE=1 ;;
        i) INPUT="$OPTARG" ;;
        \?) echo "Invalid option: -$OPTARG" >&2
            exit 2 ;;
    esac
done
shift $((OPTIND-1))

sed 's/NB\..*$//' $INPUT | "$COMPILER" compile /dev/stdin | tr -d '\n'
