#!/bin/bash

set -o errexit -o pipefail
SOLC=${SOLC-solc}

process_solc_output() {
    cat 1>&2 $1
}

TMP=$(mktemp)
trap "rm -f $TMP" EXIT

$SOLC --optimize --assemble $1 | 1>&2 tee $TMP

cat $TMP \
    | sed '1,/^Binary representation:$/d' \
    | sed '/^Text representation:/,$d' \
    | tr -d '\n' \
    | sed 's/$/\n/'
