#!/bin/sh

AS=./as-evm

set -o errexit -o pipefail

BODY=$1
INIT=${2-/dev/null}
BOOT=${3-boot.evm}

cat $INIT | tr -d '\n'

BOOT_LENGTH=$($AS boot.evm | xxd -r -p | wc -c)
sed "s/0x42/$BOOT_LENGTH/g" $BOOT | $AS 2>/dev/null | tr -d '\n'

cat $BODY | tr -d '\n'
